version: '3.8'

services:
backend:
  build:
    context: ./backend/ecommerce_backend
    dockerfile: Dockerfile
  volumes:
    - ./backend/ecommerce_backend:/app
  ports:
    - "8000:8000"
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - PYTHONUNBUFFERED=1
  restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
